name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Tool
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        dotnet: [ '3.1.410', '5.0.301' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet SDK ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ matrix.dotnet }}

      - name: Build
        shell: bash
        run: |
          dotnet tool restore
          dotnet cake
