name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Tool
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet SDK 3.1.410
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 3.1.410

      - name: Setup dotnet SDK 5.0.301
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 5.0.301

      - name: Build
        shell: bash
        run: |
          dotnet tool restore
          dotnet cake
