name: Publish package to NuGet

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dotnet: [ '3.1.410', '5.0.301' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet SDK ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ matrix.dotnet }}

      - name: Publish build
        shell: bash
        run: |
          dotnet tool restore
          dotnet cake --target="Publish" \
            --nuget-key="${{ secrets.NUGET_APIKEY }}"